const state={reviews:[],summary:null,demo:false,charts:{},filters:{industry:"All",platform:"All",app:"All"}};
const $=id=>document.getElementById(id);const fmtNumber=v=>new Intl.NumberFormat("en-US").format(v||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const stars=n=>"★".repeat(Math.min(5,Math.round(n||0)))+"☆".repeat(Math.max(0,5-Math.round(n||0)));
function matches(r){const f=state.filters;return(f.industry==="All"||r.industry===f.industry)&&(f.platform==="All"||r.platform===f.platform)&&(f.app==="All"||r.app_key===f.app)}
function aggregate(rows){const apps=new Map(),inds=new Map(),topics=new Map(),issues=new Map(),months=new Map();rows.forEach(r=>{if(!apps.has(r.app_key))apps.set(r.app_key,[]);apps.get(r.app_key).push(r);if(!inds.has(r.industry))inds.set(r.industry,[]);inds.get(r.industry).push(r);const t=r.topic||"General";topics.set(t,(topics.get(t)||0)+1);if(r.sentiment==="Negative"){const i=r.primary_issue||"General";issues.set(i,(issues.get(i)||0)+1)}const m=String(r.review_date||"").slice(0,7);if(m){if(!months.has(m))months.set(m,[]);months.get(m).push(r)}});
const sm=a=>{const n=a.length,rs=a.map(x=>Number(x.rating)).filter(x=>x>=1&&x<=5);return{review_count:n,avg_rating_from_reviews:rs.length?rs.reduce((x,y)=>x+y,0)/rs.length:null,positive_pct:n?a.filter(x=>x.sentiment==="Positive").length/n*100:0,neutral_pct:n?a.filter(x=>x.sentiment==="Neutral").length/n*100:0,negative_pct:n?a.filter(x=>x.sentiment==="Negative").length/n*100:0,one_star_pct:n?a.filter(x=>x.rating===1).length/n*100:0,two_star_pct:n?a.filter(x=>x.rating===2).length/n*100:0,actionable_review_pct:n?a.filter(x=>x.actionable).length/n*100:0}};
return{overall:sm(rows),apps:[...apps].map(([k,a])=>({app_key:k,app_name:a[0].app_name,company:a[0].company,industry:a[0].industry,...sm(a)})).sort((a,b)=>b.review_count-a.review_count),sentiment_by_industry:[...inds].map(([industry,a])=>({industry,positive:a.filter(x=>x.sentiment==="Positive").length,neutral:a.filter(x=>x.sentiment==="Neutral").length,negative:a.filter(x=>x.sentiment==="Negative").length})),topic_summary:[...topics].map(([topic,count])=>({topic,count})).sort((a,b)=>b.count-a.count),top_negative_issues:[...issues].map(([issue,count])=>({issue,count})).sort((a,b)=>b.count-a.count),trend:[...months].sort((a,b)=>a[0].localeCompare(b[0])).map(([month,a])=>({month,review_count:a.length,avg_rating:a.reduce((s,x)=>s+Number(x.rating||0),0)/a.length,negative_count:a.filter(x=>x.sentiment==="Negative").length}))};}
function chart(key,id,type,data,options={}){if(state.charts[key])state.charts[key].destroy();state.charts[key]=new Chart($(id),{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:true,position:"bottom"}},scales:{y:{beginAtZero:true,grid:{color:"#eef1f6"}},x:{grid:{display:false}}},...options}})}
function populateAppFilter(){const select=$("appFilter"),current=select.value,unique=[...new Map(state.reviews.map(r=>[r.app_key,r.app_name])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));select.innerHTML='<option value="All">All apps</option>'+unique.map(([k,n])=>`<option value="${esc(k)}">${esc(n)}</option>`).join("");if([...select.options].some(o=>o.value===current))select.value=current}
function render(){const rows=state.reviews.filter(matches),s=aggregate(rows),allo=rows.filter(r=>r.app_key==="allo_bank"),am=s.apps.find(x=>x.app_key==="allo_bank");$("kpiAlloRating").textContent=am&&am.avg_rating_from_reviews!=null?am.avg_rating_from_reviews.toFixed(2):"—";$("kpiAlloReviews").textContent=`${fmtNumber(allo.length)} written reviews in selection`;$("kpiReviews").textContent=fmtNumber(rows.length);$("kpiNegative").textContent=`${s.overall.negative_pct.toFixed(1)}%`;$("kpiActionable").textContent=`${s.overall.actionable_review_pct.toFixed(1)}%`;
chart("rating","ratingChart","bar",{labels:s.apps.map(x=>x.app_name),datasets:[{label:"Average review rating",data:s.apps.map(x=>Number(x.avg_rating_from_reviews||0).toFixed(2)),borderRadius:7}]},{indexAxis:"y",scales:{x:{min:0,max:5,grid:{color:"#eef1f6"}},y:{grid:{display:false}}}});
chart("sentiment","sentimentChart","bar",{labels:s.sentiment_by_industry.map(x=>x.industry),datasets:[{label:"Positive",data:s.sentiment_by_industry.map(x=>x.positive),borderRadius:5},{label:"Neutral",data:s.sentiment_by_industry.map(x=>x.neutral),borderRadius:5},{label:"Negative",data:s.sentiment_by_industry.map(x=>x.negative),borderRadius:5}]},{scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,beginAtZero:true,grid:{color:"#eef1f6"}}}});
const issues=s.top_negative_issues.slice(0,10);chart("issues","issueChart","bar",{labels:issues.map(x=>x.issue),datasets:[{label:"Negative review count",data:issues.map(x=>x.count),borderRadius:6}]},{indexAxis:"y"});
const topics=s.topic_summary.slice(0,10);chart("topics","topicChart","bar",{labels:topics.map(x=>x.topic),datasets:[{label:"Review count",data:topics.map(x=>x.count),borderRadius:6}]},{indexAxis:"y"});
chart("trend","trendChart","line",{labels:s.trend.map(x=>x.month),datasets:[{label:"Review volume",data:s.trend.map(x=>x.review_count),tension:.25,yAxisID:"y"},{label:"Avg. rating",data:s.trend.map(x=>x.avg_rating),tension:.25,yAxisID:"y1"}]},{scales:{y:{beginAtZero:true,grid:{color:"#eef1f6"},title:{display:true,text:"Reviews"}},y1:{position:"right",min:0,max:5,grid:{drawOnChartArea:false},title:{display:true,text:"Rating"}}}});
const tb=$("appTable").querySelector("tbody");tb.innerHTML=s.apps.length?s.apps.map(a=>`<tr><td>${esc(a.app_name)}</td><td>${esc(a.industry)}</td><td>${fmtNumber(a.review_count)}</td><td>${a.avg_rating_from_reviews!=null?a.avg_rating_from_reviews.toFixed(2):"—"}</td><td>${a.positive_pct.toFixed(1)}%</td><td>${a.negative_pct.toFixed(1)}%</td><td>${(a.one_star_pct+a.two_star_pct).toFixed(1)}%</td></tr>`).join(""):'<tr><td colspan="7"><div class="empty">No data for this filter.</div></td></tr>';$("tableNote").textContent=`${s.apps.length} apps`;
const neg=rows.filter(r=>r.sentiment==="Negative").sort((a,b)=>String(b.review_date).localeCompare(String(a.review_date))).slice(0,12);$("reviewList").innerHTML=neg.length?neg.map(r=>`<article class="review"><div class="review-top"><div><div class="review-app">${esc(r.app_name)} · ${esc(r.platform)}</div><div class="review-meta">${esc(String(r.review_date||"").slice(0,10))} · v${esc(r.app_version||"—")}</div></div><div class="review-stars">${stars(r.rating)}</div></div>${r.review_title?`<div class="review-title">${esc(r.review_title)}</div>`:""}<div class="review-text">${esc(r.review_text||"No written review text.")}</div><span class="issue-tag">${esc(r.primary_issue||"General")}</span></article>`).join(""):'<div class="empty">No negative written reviews in this selection.</div>';
$("updatedAt").textContent=state.summary?.generated_at?`Last summary build: ${new Date(state.summary.generated_at).toLocaleString()}`:"No live summary yet";}
async function load(){const [rr,sr]=await Promise.all([fetch("data/reviews.json",{cache:"no-store"}),fetch("data/summary.json",{cache:"no-store"})]);const live=await rr.json(),summary=await sr.json();if(live.reviews?.length){state.reviews=live.reviews;state.summary=summary;$("dataMode").textContent="Live collected data"}else{$("dataMode").textContent="No live data yet";const n=document.createElement("div");n.className="demo-warning";n.innerHTML='<strong>Ready for collection:</strong> no live reviews are stored yet. Run <code>run_scraper.bat</code> to populate the dashboard.';document.querySelector("main").prepend(n)}populateAppFilter();render()}
["industryFilter","platformFilter","appFilter"].forEach(id=>$(id).addEventListener("change",e=>{state.filters[id==="industryFilter"?"industry":id==="platformFilter"?"platform":"app"]=e.target.value;render()}));$("resetFilters").onclick=()=>{state.filters={industry:"All",platform:"All",app:"All"};$("industryFilter").value="All";$("platformFilter").value="All";$("appFilter").value="All";render()};
$("langEN").onclick=()=>{$("langEN").classList.add("active");$("langID").classList.remove("active")};$("langID").onclick=()=>{$("langID").classList.add("active");$("langEN").classList.remove("active")};
load().catch(e=>{document.querySelector("main").insertAdjacentHTML("afterbegin",`<div class="demo-warning"><strong>Data loading error:</strong> ${esc(e.message)}. Open the dashboard through a local HTTP server.</div>`)});
